### ISSUE TITLE
This project will be remove?

### ISSUE THREAD

**Issue by phodal** [mcollina/qest#18]
[https://github.com/phodal/diaonan](https://github.com/phodal/diaonan)

It's a fork from this repo.

**Comment by mcollina** [comment]
Hi @phodal! Almost all of what QEST was has been moved to [Ponte](http://eclipse.org/ponte), the code lives in http://github.com/eclipse/ponte. If you want to join the development team there, I will be extremely happy: I need help.

**Comment by phodal** [comment]
Hi @mcollina! I will try it.

**Comment by phodal** [comment]
@mcollina I has some problem about this.

[Eclipse-Github][Validation Error] eclipse/ponte

There was a problem validating pull request https://api.github.com/repos/eclipse/ponte/pulls/14

The pull request did not pass Eclipse validation.
The following users do not have Eclipse accounts: h@phodal.com
The following users have invalid Signed-off-by footers: h@phodal.com
